"""Structured log event name constants shared across the backend."""


class LogEvents:
    # SESSION
    SESSION_START = "SESSION_START"
    SESSION_END = "SESSION_END"

    # LOCATION
    LOCATION_UPDATE = "LOCATION_UPDATE"
    LOCATION_PERMISSION = "LOCATION_PERMISSION"

    # POI
    POI_REQUEST = "POI_REQUEST"
    POI_CACHE_HIT = "POI_CACHE_HIT"
    POI_LOADED = "POI_LOADED"
    POI_EMPTY = "POI_EMPTY"

    # NARRATION
    NARRATION_TRIGGER = "NARRATION_TRIGGER"
    NARRATION_START = "NARRATION_START"
    NARRATION_CHUNK = "NARRATION_CHUNK"
    NARRATION_COMPLETE = "NARRATION_COMPLETE"
    NARRATION_SKIP = "NARRATION_SKIP"
    POI_SELECTION = "POI_SELECTION"
    POI_SELECTION_SKIP = "POI_SELECTION_SKIP"

    # QA
    QA_START = "QA_START"
    QA_STT_DONE = "QA_STT_DONE"
    QA_ANSWER_COMPLETE = "QA_ANSWER_COMPLETE"

    # EXTERNAL
    OVERPASS_REQUEST = "OVERPASS_REQUEST"
    OVERPASS_RESPONSE = "OVERPASS_RESPONSE"
    OVERPASS_RETRY = "OVERPASS_RETRY"
    WIKI_REQUEST = "WIKI_REQUEST"
    WIKI_RESPONSE = "WIKI_RESPONSE"
    WIKI_GEOSEARCH = "WIKI_GEOSEARCH"

    # ERROR
    API_ERROR = "API_ERROR"
    UPSTREAM_FAIL = "UPSTREAM_FAIL"
