include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/shared/db/local_db.g.dart
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - prefer_const_constructors
    - prefer_final_fields
    - avoid_print
